// flow-typed signature: 02cc493edba4b37307c55c8c765085fe
// flow-typed version: <<STUB>>/eslint-plugin-import_vgit+ssh://git@github.com/benmosher/eslint-plugin-import.git/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-import/config/electron' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/config/errors' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/config/react-native' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/config/react' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/config/recommended' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/config/stage-0' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/config/warnings' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import/memo-parser/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-import/config/electron.js' {
  declare module.exports: $Exports<'eslint-plugin-import/config/electron'>;
}
declare module 'eslint-plugin-import/config/errors.js' {
  declare module.exports: $Exports<'eslint-plugin-import/config/errors'>;
}
declare module 'eslint-plugin-import/config/react-native.js' {
  declare module.exports: $Exports<'eslint-plugin-import/config/react-native'>;
}
declare module 'eslint-plugin-import/config/react.js' {
  declare module.exports: $Exports<'eslint-plugin-import/config/react'>;
}
declare module 'eslint-plugin-import/config/recommended.js' {
  declare module.exports: $Exports<'eslint-plugin-import/config/recommended'>;
}
declare module 'eslint-plugin-import/config/stage-0.js' {
  declare module.exports: $Exports<'eslint-plugin-import/config/stage-0'>;
}
declare module 'eslint-plugin-import/config/warnings.js' {
  declare module.exports: $Exports<'eslint-plugin-import/config/warnings'>;
}
declare module 'eslint-plugin-import/memo-parser/index.js' {
  declare module.exports: $Exports<'eslint-plugin-import/memo-parser/index'>;
}
