// flow-typed signature: cd7db524070c5e6cc82f01ac04698e37
// flow-typed version: <<STUB>>/eslint-plugin-you-dont-need-lodash-underscore_v^6.3.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-you-dont-need-lodash-underscore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-you-dont-need-lodash-underscore' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-you-dont-need-lodash-underscore/lib/rules/all' {
  declare module.exports: any;
}

declare module 'eslint-plugin-you-dont-need-lodash-underscore/tests/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-you-dont-need-lodash-underscore/tests/lib/rules/all' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-you-dont-need-lodash-underscore/index' {
  declare module.exports: $Exports<'eslint-plugin-you-dont-need-lodash-underscore'>;
}
declare module 'eslint-plugin-you-dont-need-lodash-underscore/index.js' {
  declare module.exports: $Exports<'eslint-plugin-you-dont-need-lodash-underscore'>;
}
declare module 'eslint-plugin-you-dont-need-lodash-underscore/lib/rules/all.js' {
  declare module.exports: $Exports<'eslint-plugin-you-dont-need-lodash-underscore/lib/rules/all'>;
}
declare module 'eslint-plugin-you-dont-need-lodash-underscore/tests/index.js' {
  declare module.exports: $Exports<'eslint-plugin-you-dont-need-lodash-underscore/tests/index'>;
}
declare module 'eslint-plugin-you-dont-need-lodash-underscore/tests/lib/rules/all.js' {
  declare module.exports: $Exports<'eslint-plugin-you-dont-need-lodash-underscore/tests/lib/rules/all'>;
}
