/*
 -------------------------------------------------------------------------------------------------------------------------------
 Copyright © 2017 Alexandre Mueller Nicastro
 All rights reserved.

 THE SOURCE CODE CONTAINED HEREIN AND IN RELATED FILES ARE PROPERTY OF ALEXANDRE MUELLER NICASTRO.
 UNDER NO CIRCUMSTANCES MAY ANY PORTION OF THE SOURCE CODE BE DISTRIBUTED, DISCLOSED OR OTHERWISE
 MADE AVAILABLE TO ANY THIRD PARTY WITHOUT THE EXPRESS WRITTEN CONSENT OF ALEXANDRE MUELLER NICASTRO.

 UNDER NO CIRCUMSTANCES MAY THE SOURCE CODE BE USED IN WHOLE OR IN PART FOR ANY OTHER SOFTWARE
 THEN THE ORIGINAL INTEND.

 THE LICENSE AGREEMENT ACCOMPANYING THE PRODUCT DOES NOT PROVIDE ANY RIGHTS REGARDING THE SOURCE
 CODE CONTAINED HEREIN.

 THIS COPYRIGHT NOTICE MAY NOT BE REMOVED FROM THIS FILE.
 -------------------------------------------------------------------------------------------------------------------------------
 */
